# Generated by Django 6.0.1 on 2026-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('poytaxti', models.CharField(max_length=50)),
                ('aholisi', models.IntegerField()),
                ('mustaqillik_yili', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
